#whenver we work with docker, need to mention sudo required. so that travis environment can prepare accordingly.
sudo: required

#letting travis know that, we need docker preinstalled.
services: 
  - docker

# here testing will be done with dev file and deployment will be done using prod Dockerfile.
before_install: 
  - docker build -t sendevour/docker-react -f Dockerfile.dev .

# action to be performed for testing. here, -- --coverage is added to avoid npm run test waiting for user to press q.
# with -- --coverage didnt work, https://stackoverflow.com/questions/55926939/node-in-docker-npm-test-and-exit 
# above link helped for exit with -e CI=true flag
script:
 - docker run -e CI=true sendevour/docker-react npm run test -- --coverage

#AWS section for deployment
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-331576726827"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY